server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.2:3306/minzhengju_clear?useUnicode=true&characterEncoding=UTF-8&autoReconnect\=true&failOverReadOnly\=false
    username: root
    password: localhost
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.zoop.entity