my-config:
  appName: cloud-config-repo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.239.143:3306/zoop_sql?useUnicode=true&characterEncoding=UTF-8&autoReconnect\=true&failOverReadOnly\=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.zoop.entity